[package]
name = "accoutrements"
version = "0.3.0-alpha.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
regex = "1.11.1"
toml = "0.8.19"
serde = { version = "1.0.217", features = ["derive"] }
